<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Services\PasswordHasherService.cs" />
    <Compile Remove="Services\PasswordHashService.cs" />
    <Compile Remove="Services\RoleService.cs" />
    <Compile Remove="Services\UserRegisterService.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="RapidFireUI" Version="8.*" />
  </ItemGroup>
</Project>
